[package]
name = "slacktus"
version = "0.1.0"
authors = ["David Bonet Montes <webbonet@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32"
reqwest = "0.9.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

